async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

spring:
    datasource:
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://<IP>:3306/<DB>?autoConnect=true
        databaseName:
        serverName:
        username: <user>
        password: <password>
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

    mail:
        host: localhost
        port: 25
        user:
        password:
        protocol: smtp
        tls: false
        auth: false
        from: route_tracker@localhost

    jpa:
        database-platform: org.hibernate.dialect.MySQLInnoDBDialect
        database: MYSQL
        openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true

    thymeleaf:
        mode: XHTML
        cache: false

swagger:
    title: API
    description:
    termsOfServiceUrl:
    contact:
    license:
    licenseUrl:
